DROP TABLE IF EXISTS BOOTH_INFO;

CREATE TABLE BOOTH_INFO(
        ID INT NOT NULL AUTO_INCREMENT COMMENT '展位id，自增主键',
        PRICE BIGINT COMMENT '展位价格',
        STATE CHAR(1) DEFAULT '1' COMMENT '展位状态，1未购买，2购买中，3已购买',
        COMPANY_ID INT COMMENT '公司id',
        CREATE_DT TIMESTAMP ,
        CREATER VARCHAR(19),
        UPDATE_DT TIMESTAMP ,
        UPDATER VARCHAR(19),
        PRIMARY KEY(ID)
)ENGINE=INNODB DEFAULT CHARSET='UTF8' COMMENT '展位信息表'



INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('80000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('80000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('80000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('80000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('80000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('80000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('80000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('80000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);
INSERT INTO BOOTH_INFO (PRICE,UPDATE_DT) VALUES ('70000',CURRENT_TIMESTAMP);


