CREATE EVENT `NewEvent`
ON SCHEDULE EVERY 5 MINUTE
ON COMPLETION NOT PRESERVE
ENABLE
COMMENT '每隔5分钟检测一次展位信息表BOOTH_INFO,将10分前被更新为状态2购买中的展位重新更新为未购买'
DO
UPDATE BOOTH_INFO SET STATE=1,COMPANY_ID=NULL WHERE STATE=2 AND TIMESTAMPDIFF(minute,update_dt,current_timestamp)>10;
